//! Writes the layout into `lua/monitors.lua` between marker comments, leaving
//! everything outside the markers (the human commentary) untouched.

use crate::hypr::MonitorCfg;
use crate::model::Layout;
use anyhow::{Context, Result};
use std::path::Path;

pub const BEGIN: &str = "-- BEGIN hyprdisplays (generated by the hyprdisplays app; edit there, or between these markers at your own risk)";
pub const END: &str = "-- END hyprdisplays";

pub fn default_path() -> std::path::PathBuf {
    dirs::config_dir().unwrap_or_default().join("hypr/lua/monitors.lua")
}

fn lua_rule(m: &MonitorCfg) -> String {
    let mut s = String::new();
    s.push_str(&format!("-- {} ({})\n", m.name, m.description));
    s.push_str("hl.monitor({\n");
    s.push_str(&format!("    output   = \"desc:{}\",\n", m.description.replace('"', "\\\"")));
    s.push_str(&format!("    mode     = \"{}\",\n", m.mode));
    s.push_str(&format!("    position = \"{}x{}\",\n", m.x, m.y));
    s.push_str(&format!("    scale    = {},\n", crate::hypr::fmt_scale(m.scale)));
    s.push_str(&format!("    vrr      = {},\n", if m.vrr { 1 } else { 0 }));
    if let Some(mir) = &m.mirror {
        s.push_str(&format!("    mirror   = \"{mir}\",\n"));
    }
    if !m.enabled {
        s.push_str("    disabled = true,\n");
    }
    s.push_str("})\n");
    s
}

pub fn render_block(layout: &Layout) -> String {
    let mut s = String::new();
    s.push_str(BEGIN);
    s.push('\n');
    s.push_str("-- Catch-all for anything unlisted (\"preferred\", not highrr: a TV's top\n");
    s.push_str("-- refresh mode can be 800x600@60.32, which highrr picks over 1080p@60).\n");
    s.push_str("hl.monitor({ output = \"\", mode = \"preferred\", position = \"auto\", scale = 1, vrr = 1 })\n\n");
    for m in &layout.monitors {
        s.push_str(&lua_rule(m));
        s.push('\n');
    }
    s.push_str(END);
    s.push('\n');
    s
}

/// Replace (or append) the marked block in `existing`.
pub fn splice(existing: &str, block: &str) -> String {
    match (existing.find(BEGIN), existing.find(END)) {
        (Some(b), Some(e)) if e > b => {
            let after = existing[e..].find('\n').map(|n| e + n + 1).unwrap_or(existing.len());
            format!("{}{}{}", &existing[..b], block, &existing[after..])
        }
        _ => {
            let mut out = existing.to_string();
            if !out.ends_with('\n') { out.push('\n'); }
            out.push('\n');
            out.push_str(block);
            out
        }
    }
}

pub fn write(path: &Path, layout: &Layout) -> Result<()> {
    let existing = std::fs::read_to_string(path).unwrap_or_default();
    let out = splice(&existing, &render_block(layout));
    let tmp = path.with_extension("lua.tmp");
    std::fs::write(&tmp, out).with_context(|| format!("writing {}", tmp.display()))?;
    std::fs::rename(&tmp, path).with_context(|| format!("renaming into {}", path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::hypr::parse_monitors;

    #[test]
    fn splice_preserves_text_outside_markers() {
        let l = Layout::from_live(&parse_monitors(include_str!("../tests/fixtures/monitors_all.json")).unwrap());
        let block = render_block(&l);
        let existing = format!("-- hand comment\nhl.monitor({{ output = \"x\" }})\n\n{BEGIN}\nold stuff\n{END}\n-- trailing\n");
        let out = splice(&existing, &block);
        assert!(out.starts_with("-- hand comment\nhl.monitor({ output = \"x\" })\n\n"));
        assert!(out.ends_with("-- trailing\n"));
        assert!(!out.contains("old stuff"));
        assert!(out.contains("desc:ASUSTek COMPUTER INC VY279HGR TCLMTR040596"));
        assert!(out.contains("position = \"1920x0\""));
        // idempotent
        assert_eq!(splice(&out, &block), out);
    }

    #[test]
    fn splice_appends_when_no_markers() {
        let out = splice("-- only comments\n", "BLOCK\n");
        assert_eq!(out, "-- only comments\n\nBLOCK\n");
    }
}
